FROM python:3.7.3-alpine
ENV PYTHONUNBUFFERED 1
RUN mkdir /impressiveUploader
WORKDIR /impressiveUploader
ADD requirements.txt /impressiveUploader/
RUN pip install -r requirements.txt
ADD ./ /impressiveUploader/
CMD ["python", "mysite/manage.py", "runserver", "0.0.0.0:8001"]
